version: "3"

services:
  database:
    image: postgres:latest
    
    expose:
      - "5432"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB='rdc'
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='postgres'
      
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    links:
      - node1:node1
    depends_on:
      - node1
      - database
    ports:
      - "8080:80"
      - "8083:443"
    expose:
      - "80"
      - "443"

  node1:
    build: 
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    depends_on:
      - database


  
